### PR TITLE
Fix Action window in UVEditor not scrollable.

### PR DESCRIPTION
**Pull request by thomas-tu**
**Goal of this PR:**
In the UV Editor, user can only scroll the UV view (grid) and not the actions window that is embedded. This PR fixes that issue by checking when we scroll if mouse is hovering the actions window. If so, we don't scroll the UV view and don't consume the event.

Fix this case: https://unity3d.atlassian.net/browse/WB-1260

### CODE REVIEW

**Comment by gabrielw-us** [comment]
@thomas-tu Bug in branch: does not scroll if nothing selected, or if just one vertex selected.

**Comment by karl-** [comment]
💯

**Comment by gabrielw-us** [comment]
@thomas-tu did you see my note? is bugged :( I don't see any further commits after that?

**Comment by gabrielw-us** [comment]
Created a new Jira since this got merged: https://unity3d.atlassian.net/browse/WB-1306

**Pull request merged**
