### PR TITLE
Allow picking on a Terrain when trying to get the best plane.

### PR DESCRIPTION
**Pull request by MartinImgSpc**
Modified FindBestPlane to handle picking Terrain.
Note: Tried to create a unit test without success because FindBestPlane relies on UnityEditor.HandleUtility.PickGameObject which cannot be called outside OnGui calls.

### CODE REVIEW

**Comment by thomas-tu** [comment]
The current changes would help pick the first point on a terrain and define a plane that would be used to build the polyshape but won't prevent creating points behind a terrain on that plane. Is it something we want for the Polyshape tool? @karl-  @gabrielw-us 

I would maybe expect to have my first three points stick to terrain (3 points to build a plane vs. using the first point normal).

**Comment by gabrielw-us** [comment]
> I would maybe expect to have my first three points stick to terrain (3 points to build a plane vs. using the first point normal).

That could be useful as a separate feature, sure! I'd say make a separate feature JIRA for that, we can discuss? For this task, I just wanted to ensure the standard functionality works (first click sets initial position and plane).

**Comment by karl-** [comment]
> I would maybe expect to have my first three points stick to terrain (3 points to build a plane vs. using the first point normal).

I think this would probably be good to support for any object intersecting the first 3 rays. However I agree with @gabrielw-us, let's create a separate case for that.

**Comment by thomas-tu** [comment]
Thanks guys!

**Comment by MartinImgSpc** [comment]
Thank you!

**Pull request merged**
