### PR TITLE
Fixed Issue Where Picking Wouldn't Work for Some Users

### PR DESCRIPTION
**Pull request by antoine-unity**

### CODE REVIEW

**Comment by gabrielw-us** [comment]
Is there a fogbugz/jira with a good repro? Not sure I have that 100%.

**Comment by gabrielw-us** [comment]
Yup, seems fine, just not sure if I'm testing correctly.

**Comment by gabrielw-us** [comment]
@antoine-unity haaalp (see above)

**Comment by karl-** [comment]
> Is there a fogbugz/jira with a good repro? Not sure I have that 100%.

We never did find a good repro for getting into this state, but if we set it manually in code we can reproduce the exact symptoms.

**Pull request merged**
