### PR TITLE
ProBuilder 6 - Improvements part 2

### PR DESCRIPTION
**Pull request by lopezt-unity**
### Purpose of this PR

This PR is based on a previous work from @karl- (branch `remove-window-dependency`) to remove the dependency on the ProBuilder Editor window:
- The window is not needed anymore to use the ProBuilder functionalities.
- ProBuilder is now usable through the ProBuilder context and the Scene View ContextMenu.
- Vertex / Edge / Face modes are now accessible through the tool settings overlay in the ProBuilder Context.
- Creation tool (Create Shape and Create PolyShape) are accessible as global tools in the main toolbar.
- EditShape / EditPolyShape / Cut Tool are component tools only available within the ProBuilder Context.
- Improvement regarding the ProBuilderShape pivot creation and storage.
- Added all the actions in the ShortcutManager so that users can customize them.

### Links

**Jira:** https://jira.unity3d.com/browse/STO-3109

### Comments to Reviewers

@claudiaantoun , I would need your help, is it possible to add the shortcut on the MenuItem in the Scene Context Menu when one exists ? Thanks :) (I think it's not possible in the main menus, but I wish at least it would be in the context menu)

### CODE REVIEW

**Review by gabrielw-us — APPROVED** [review]
Super work Thomas!

**Review by xianenli30 — APPROVED** [review]
Finally! Ready to give the final approval. See test coverage below:
-[Testrail](https://qatestrail.hq.unity3d.com/index.php?/runs/view/46350&group_by=cases:section_id&group_order=asc)(note that failed tests are known issues as discussed)

-[bug tracker](https://docs.google.com/document/d/1yyIXEgwhb-i6ibXTqpi4FwpOkDwlBHS60FRJ6i_Cac4/edit)
p.s. I looked at the grid and snap tool as well per request from @gabrielw-us, Thomas pushed a fix for a case where you have 0 displacement and mesh doesn't update.

**Comment by karl-** [comment]
I'm out sick all this week, adding Mod to cover for my review.

**Comment by karl-** [comment]
object picking seems to interfere with element selection

[face-selection.webm](https://github.com/Unity-Technologies/com.unity.probuilder/assets/1683036/a5eafdff-8e4a-4192-b5a2-06dbc00e231d)

**Comment by karl-** [comment]
clicking off a selected face, then undoing does not restore the face selection

[selection-undo.webm](https://github.com/Unity-Technologies/com.unity.probuilder/assets/1683036/86516352-5fa9-4a96-91a0-809ea0a802e7)

**Comment by karl-** [comment]
shift+click on other probuilder mesh clears the selection, but does add the object to the active selection. it should keep the face selection and append the object to the active selection, with the next click adding to the face selection

[shift-select-other.webm](https://github.com/Unity-Technologies/com.unity.probuilder/assets/1683036/0ad7381c-4b11-456a-9b75-de3c8584a8a0)

**Comment by karl-** [comment]
a rect select that doesn't capture any elements kicks me out of mesh editing
[rect-exits-mode.webm](https://github.com/Unity-Technologies/com.unity.probuilder/assets/1683036/9a7bbb4d-9566-46bc-a424-59a46a9ca29f)

**Review by modrimkus-unity — COMMENTED** [review]
Getting quite a few null ref exceptions while switching context and selecting elements:

`NullReferenceException: Object reference not set to an instance of an object
UnityEditor.RectSelection.OnNormalRectSelection (UnityEditor.ShortcutManagement.ShortcutArguments args) (at /Users/mod.rimkus/Development/unity_2023_1/Editor/Mono/SceneView/RectSelection.cs:69)
UnityEditor.ShortcutManagement.Trigger.ExecuteShortcut (UnityEditor.ShortcutManagement.ShortcutEntry entry, UnityEditor.ShortcutManagement.ShortcutStage stage, System.Object context) (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/Trigger.cs:421)
UnityEditor.ShortcutManagement.Trigger.HandleKeyEvent (UnityEngine.Event evt, UnityEditor.ShortcutManagement.IContextManager contextManager) (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/Trigger.cs:225)
UnityEditor.ShortcutManagement.ShortcutController.HandleKeyEvent (UnityEngine.Event evt) (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/ShortcutController.cs:289)
UnityEditor.ShortcutManagement.ShortcutIntegration.EventHandler () (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/ShortcutController.cs:135)
UnityEditor.EditorApplication.Internal_CallGlobalEventHandler () (at /Users/mod.rimkus/Development/unity_2023_1/Editor/Mono/EditorApplication.cs:490)`
Don't have exact repro steps but pretty close in the attached video:

https://github.com/Unity-Technologies/com.unity.probuilder/assets/80063635/2d2badbb-2019-45d3-9df4-84d93aa1d177

**Review by modrimkus-unity — COMMENTED** [review]
Possibly unrelated to PR, but is the cut tool icon supposed to be this large? (attaching photo as screenshot doesn't capture the icon for some reason):
IMG_2054

**Comment by lopezt-unity** [comment]
> Getting quite a few null ref exceptions while switching context and selecting elements:
> 
> `NullReferenceException: Object reference not set to an instance of an object UnityEditor.RectSelection.OnNormalRectSelection (UnityEditor.ShortcutManagement.ShortcutArguments args) (at /Users/mod.rimkus/Development/unity_2023_1/Editor/Mono/SceneView/RectSelection.cs:69) UnityEditor.ShortcutManagement.Trigger.ExecuteShortcut (UnityEditor.ShortcutManagement.ShortcutEntry entry, UnityEditor.ShortcutManagement.ShortcutStage stage, System.Object context) (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/Trigger.cs:421) UnityEditor.ShortcutManagement.Trigger.HandleKeyEvent (UnityEngine.Event evt, UnityEditor.ShortcutManagement.IContextManager contextManager) (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/Trigger.cs:225) UnityEditor.ShortcutManagement.ShortcutController.HandleKeyEvent (UnityEngine.Event evt) (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/ShortcutController.cs:289) UnityEditor.ShortcutManagement.ShortcutIntegration.EventHandler () (at /Users/mod.rimkus/Development/unity_2023_1/Modules/ShortcutManagerEditor/ShortcutController.cs:135) UnityEditor.EditorApplication.Internal_CallGlobalEventHandler () (at /Users/mod.rimkus/Development/unity_2023_1/Editor/Mono/EditorApplication.cs:490)` Don't have exact repro steps but pretty close in the attached video:
> 
>  Screen.Recording.2023-11-22.at.1.38.43.PM.mov

This is solved by a trunk PR on 2023.3.0a16

**Comment by lopezt-unity** [comment]
> object picking seems to interfere with element selection
> 
>  face-selection.webm

This was already the case in previous PB versions (here 5.2), that's actually a problem when the mouse does not mouse between clicks.

pb5 2-selectioncycling

**Review by modrimkus-unity — COMMENTED** [review]
Shape settings seems to consistently throw if changed before drawing 
https://github.com/Unity-Technologies/com.unity.probuilder/assets/80063635/1937eb42-1fc0-453d-89fb-5d8abd3e716b

**Comment by lopezt-unity** [comment]
> shift+click on other probuilder mesh clears the selection, but does add the object to the active selection. it should keep the face selection and append the object to the active selection, with the next click adding to the face selection
> 
>  shift-select-other.webm

The problem on that one is that Changing the object selection is rebuilding the active trackers, which reactivate GameObject context, and reactivate PBContext, which was clearing the face selection.

**Comment by lopezt-unity** [comment]
> Shape settings seem to consistently throw if changed before drawing https://github.com/Unity-Technologies/com.unity.probuilder/assets/80063635/1937eb42-1fc0-453d-89fb-5d8abd3e716b

Fixed!

**Comment by modrimkus-unity** [comment]
Minor thing but entering the context with a newly selected PB go will flash the previous selected elements on other objects for a split second.

https://github.com/Unity-Technologies/com.unity.probuilder/assets/80063635/5e6f446f-8c0d-490e-b93f-827d0afd0d9a

**Review by modrimkus-unity — APPROVED** [review]
Approving after a peer review session and multiple hours of manual testing. Great work!

Minor note/not bug:

https://github.com/Unity-Technologies/com.unity.probuilder/assets/80063635/0aa72030-eea7-4869-8d30-04b17e494f7b

It would be nice if the "Shape settings" overlay instead of always saying "(New Shape)" which is not very useful and can be a bit disorienting (i.e. which exact shape I'm in atm) it would say "(New Cube/Arch/etc.)". Right now it only changes to "Cube/Arch/etc." after you've already created the shape.

**Comment by claudiaantoun** [comment]
When enabling the PolyShape tool from the Tools Overlay, the PB Tool Context appears. When enabling that Tool Context, it switches back to the Game Object Context.

ContextSwitchBug

**Review by claudiaantoun — APPROVED** [review]
My review was mostly done in-person or on Slack by sending the bugs I found to Thomas directly. Amazing work Thom!

**Comment by lopezt-unity** [comment]
Merging PR,
Other problems will be addressed in follow-up smaller PRs

**Pull request merged**
