### PR TITLE
Fix building runtime editing example to standalone

### PR DESCRIPTION
**Pull request by karl-**
https://fogbugz.unity3d.com/f/cases/1165683

Fixes issues when building the runtime editing example to a player.

- Missing references to materials and shaders
- An uninitialized lookup dictionary
- Add a readme for a common mistake (forgetting to disable script stripping)

### CODE REVIEW

**Comment by gabrielw-us** [comment]
In the standalone build, click-drag on face just pans my camera
In the editor Play mode, click-drag works to move faces, but I see an enormous axis indicator

image

**Comment by karl-** [comment]
> In the standalone build, click-drag on face just pans my camera

You have to disable "Script Stripping" in the ProBuilder preferences for this example to work. It's mentioned in the new readme.

>  In the editor Play mode, click-drag works to move faces, but I see an enormous axis indicator

✅

**Comment by gabrielw-us** [comment]
🤦‍♂ of course, and you just mentioned that the other day :D

re-checking 👍

**Comment by karl-** [comment]
@gabrielw-us c75908d09e0a6846747ec6232ff174727a524234 sets a reasonable line width

**Comment by JoelFortin** [comment]
Forget what I said about the script missing your changes ... just realized I used the scripts that was in the attached project and not your new version of the script from the package. Fire Away !!

**Pull request merged**
